// <auto-generated />
using System;
using ASPNETMVC.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASPNETMVC.Migrations
{
    [DbContext(typeof(AjaxDropDownContext))]
    [Migration("20260922090526_AddDistrictToEmployee")]
    partial class AddDistrictToEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASPNETMVC.Models.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("districtId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<string>("DistrictName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("districtName");

                    b.Property<int?>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("stateId");

                    b.HasKey("DistrictId")
                        .HasName("pk_distId");

                    b.HasIndex("StateId");

                    b.ToTable("districts", (string)null);
                });

            modelBuilder.Entity("ASPNETMVC.Models.Employee", b =>
                {
                    b.Property<int>("EmpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("empId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpId"));

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("EmpDob")
                        .HasColumnType("date")
                        .HasColumnName("empDOB");

                    b.Property<string>("EmpGender")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("empGender");

                    b.Property<string>("EmpName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("empName");

                    b.Property<int?>("StateId")
                        .HasColumnType("int")
                        .HasColumnName("stateId");

                    b.HasKey("EmpId")
                        .HasName("pk_empId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("StateId");

                    b.ToTable("Employee", (string)null);
                });

            modelBuilder.Entity("ASPNETMVC.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stateId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"));

                    b.Property<string>("StateName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("stateName");

                    b.HasKey("StateId")
                        .HasName("pk_state");

                    b.ToTable("states", (string)null);
                });

            modelBuilder.Entity("ASPNETMVC.Models.District", b =>
                {
                    b.HasOne("ASPNETMVC.Models.State", "State")
                        .WithMany("Districts")
                        .HasForeignKey("StateId")
                        .HasConstraintName("fk_stateId");

                    b.Navigation("State");
                });

            modelBuilder.Entity("ASPNETMVC.Models.Employee", b =>
                {
                    b.HasOne("ASPNETMVC.Models.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("ASPNETMVC.Models.State", "State")
                        .WithMany("Employees")
                        .HasForeignKey("StateId")
                        .HasConstraintName("fk_stateId1");

                    b.Navigation("District");

                    b.Navigation("State");
                });

            modelBuilder.Entity("ASPNETMVC.Models.State", b =>
                {
                    b.Navigation("Districts");

                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
